version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
ignore:
  - dependency-name: govuk_chat_private
