version: 2
updates:
  - package-ecosystem: bundler
    registries: "*"
    insecure-external-code-execution: allow
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
      exclude:
        - gds-api-adapters
        - gds-sso
        - govuk_*
        - rubocop-govuk
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 3
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
