version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: bundler
    registries: "github"
    insecure-external-code-execution: allow
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
