answered:
  label: "Answered"
  label_colour: "green"
  description:
  label_and_description:
pending:
  label: "Pending"
  label_colour: "light-blue"
  description:
  label_and_description:
clarification:
  label: "Clarification"
  label_colour: "turquoise"
  description: "question routing requested more information"
  label_and_description: "Clarification - question routing requested more information"
unanswerable_question_routing:
  label: "Unanswerable"
  label_colour: "blue"
  description: "question routing deemed unanswerable"
  label_and_description: "Unanswerable - question routing deemed unanswerable"
unanswerable_llm_cannot_answer:
  label: "Unanswerable"
  label_colour: "blue"
  description: "LLM couldn't answer the question"
  label_and_description: "Unanswerable - LLM couldn't answer the question"
unanswerable_no_govuk_content:
  label: "Unanswerable"
  label_colour: "blue"
  description: "no GOV.UK content found"
  label_and_description: "Unanswerable - no GOV.UK content found"
guardrails_answer:
  label: "Guardrails"
  label_colour: "yellow"
  description: "answer guardrails triggered"
  label_and_description: "Guardrails - answer guardrails triggered"
guardrails_forbidden_terms:
  label: "Guardrails"
  label_colour: "yellow"
  description: "forbidden terms detected"
  label_and_description: "Guardrails - forbidden terms detected"
guardrails_jailbreak:
  label: "Guardrails"
  label_colour: "yellow"
  description: "jailbreak guardrails triggered"
  label_and_description: "Guardrails - jailbreak guardrails triggered"
guardrails_question_routing:
  label: "Guardrails"
  label_colour: "yellow"
  description: "question routing guardrails triggered"
  label_and_description: "Guardrails - question routing guardrails triggered"
banned:
  label: "Abort"
  label_colour: "purple"
  description: "user cannot generate answers due to shadow banning"
  label_and_description: "Banned - user cannot generate answers due to shadow banning"
error_answer_guardrails:
  label: "Error"
  label_colour: "red"
  description: "invalid format from answer guardrails LLM call"
  label_and_description: "Error - invalid format from answer guardrails LLM call"
error_answer_service_error:
  label: "Error"
  label_colour: "red"
  description: "received error from LLM"
  label_and_description: "Error - received error from LLM"
error_context_length_exceeded:
  label: "Error"
  label_colour: "red"
  description: "too many tokens sent to LLM"
  label_and_description: "Error - too many tokens sent to LLM"
error_jailbreak_guardrails:
  label: "Error"
  label_colour: "red"
  description: "invalid format from jailbreak guardrails LLM call"
  label_and_description: "Error - invalid format from jailbreak guardrails LLM call"
error_non_specific:
  label: "Error"
  label_colour: "red"
  description: "unexpected system error"
  label_and_description: "Error - unexpected system error"
error_timeout:
  label: "Error"
  label_colour: "red"
  description: "no answer after configured timeout"
  label_and_description: "Error - no answer after configured timeout"
error_question_routing_guardrails:
  label: "Error"
  label_colour: "red"
  description: "error from question routing guardrails LLM call"
  label_and_description: "Error - from question routing guardrails LLM call"
