success:
  label: "Success"
  label_colour: "green"
  description:
  label_and_description:
pending:
  label: "Pending"
  label_colour: "yellow"
  description:
  label_and_description:
abort_answer_guardrails:
  label: "Abort"
  label_colour: "orange"
  description: "answer guardrails triggered"
  label_and_description: "Abort - answer guardrails triggered"
abort_forbidden_terms:
  label: "Abort"
  label_colour: "orange"
  description: "failed forbidden terms check"
  label_and_description: "Abort - failed forbidden terms check"
abort_jailbreak_guardrails:
  label: "Abort"
  label_colour: "orange"
  description: "jailbreak guardrails triggered"
  label_and_description: "Abort - jailbreak guardrails triggered"
abort_llm_cannot_answer:
  label: "Abort"
  label_colour: "orange"
  description: "LLM couldn't answer the question"
  label_and_description: "Abort - LLM couldn't answer the question"
abort_output_guardrails:
  label: "Abort"
  label_colour: "orange"
  description: "output guardrails triggered"
  label_and_description: "Abort - output guardrails triggered"
abort_no_govuk_content:
  label: "Abort"
  label_colour: "orange"
  description: "no GOV.UK content found"
  label_and_description: "Abort - no GOV.UK content found"
abort_question_routing:
  label: "Abort"
  label_colour: "orange"
  description: "unsuitable question asked"
  label_and_description: "Abort - unsuitable question asked"
error_answer_guardrails:
  label: "Error"
  label_colour: "red"
  description: "invalid format from answer guardrails LLM call"
  label_and_description: "Error - invalid format from answer guardrails LLM call"
abort_question_routing_token_limit:
  label: "Abort"
  label_colour: "orange"
  description: "completion token limit reached"
  label_and_description: "Abort - completion token limit reached"
error_answer_service_error:
  label: "Error"
  label_colour: "red"
  description: "received error from LLM"
  label_and_description: "Error - received error from LLM"
error_context_length_exceeded:
  label: "Error"
  label_colour: "red"
  description: "too many tokens sent to LLM"
  label_and_description: "Error - too many tokens sent to LLM"
error_jailbreak_guardrails:
  label: "Error"
  label_colour: "red"
  description: "invalid format from jailbreak guardrails LLM call"
  label_and_description: "Error - invalid format from jailbreak guardrails LLM call"
error_output_guardrails:
  label: "Error"
  label_colour: "red"
  description: "invalid format from output guardrails LLM call"
  label_and_description: "Error - invalid format from output guardrails LLM call"
error_non_specific:
  label: "Error"
  label_colour: "red"
  description: "unexpected system error"
  label_and_description: "Error - unexpected system error"
error_timeout:
  label: "Error"
  label_colour: "red"
  description: "no answer after configured timeout"
  label_and_description: "Error - no answer after configured timeout"
error_question_routing:
  label: "Error"
  label_colour: "red"
  description: "invalid response from question routing LLM call"
  label_and_description: "Error - invalid response from question routing LLM call"
